Corrige CI definitivo: ignora integridade e roda testes E2E
LIA SILVA@DESKTOP-6T5JVV5 MINGW64 ~/extens-o-chrome-boot2- (main)
$ git pull origin main --rebase
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 1.45 KiB | 61.00 KiB/s, done.
From https://github.com/Carlos-Eduardo-Araujo/extens-o-chrome-boot2-
 * branch            main       -> FETCH_HEAD
    1427707..d80d796  main       -> origin/main
    Auto-merging .github/workflows/ci.yml
    CONFLICT (content): Merge conflict in .github/workflows/ci.yml
    error: could not apply af0100c... Corrige CI definitivo: ignora
    integridade e roda testes E2E
    hint: Resolve all conflicts manually, mark them as resolved with
    hint: "git add/rm <conflicted_files>", then run "git rebase
    --continue".
    hint: You can instead skip this commit: run "git rebase --skip".
    hint: To abort and get back to the state before "git rebase", run
    "git rebase --abort".
    hint: Disable this message with "git config advice.mergeConflict
    false"
    Corrige CI definitivo: ignora integridade e roda testes E2E

    # Conflicts:
    #       .github/workflows/ci.yml

    # Please enter the commit message for your changes. Lines starting
    # with '#' will be ignored, and an empty message aborts the commit.
    #
    # interactive rebase in progress; onto d80d796
    # Last command done (1 command done):
    #    pick af0100c Corrige CI definitivo: ignora integridade e roda
    testes E2E
    # No commands remaining.
    # You are currently rebasing branch 'main' on 'd80d796'.
    #
    # Changes to be committed:
    #       modified:   .github/workflows/ci.yml
    #
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    ~
    .git/COMMIT_EDITMSG [unix] (20:29 19/10/2025)
    1,1 All
    "~/extens-o-chrome-boot2-/.git/COMMIT_EDITMSG" [unix] 17L, 554B      # interactive rebase in progress; onto d80d796